[package]
name = "tfix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tfix_derive = { version = "*", path = "tfix_derive" }
